{% set version = "2.0.3" %}
{% set sha256 = "6c5585b64ad23b51e9da981948cd9c0d6f8311f45712709b1fe090c3aa08191d" %}

package:
  name: EviAnn
  version: {{ version }}

source:
  url: https://github.com/alekseyzimin/EviAnn_release/releases/download/v{{ version }}/EviAnn-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [osx]
  number: 0
  run_exports:
    - {{ pin_subpackage('eviann', max_pin="x.x") }}

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
  host:
    - perl
    - zlib
    - bzip2
  run:
    - perl
    - makeblastdb
    - blastp
    - hisat2
    - hisat2-build
    - minimap2
    - wget

test:
  commands:
    - eviann.sh --version

about:
  home: https://github.com/alekseyzimin/EviAnn-release
  license: GPLv3
  license_file: LICENSE
  summary: Evidence-based eukaryotic genome annotation software

extra:
  additional-platforms:
    - linux-aarch64


